### ISSUE TITLE
Disable ES index off Asynchronous event logs 

### ISSUE THREAD

**Issue by joachimVT** [aligent/magento-async-events#60]
Hi 
First off all great work on this package it's really powerful! 

We are getting some errors on the indexing off Asynchronous events to ES. Because we are using the Elasticsuite module for Elastic Search indexing the default ES client is not configured. 

I know there is a configuration option to enable / disable indexing, however disabling the indexing still triggers the error. Would there be any way around to completely remove the event indexing or make it compatible with elasticsuite module ? 

Thanks.

**Comment by gowrizrh** [comment]
Thanks, would you be able to provide more information / stack traces on what error you're seeing and when?

**Comment by joachimVT** [comment]
Hi @gowrizrh 

Sure

Magento version : 2.4.6-p2 - Magento community edition
smile/elasticsuite version: 2.11.5.1

## Steps to reproduce: 
1. require package via composer
2. run setup:upgrade
3. run index:reindex

## Expected result:
Index completed with no exceptions. 

## Actual result:
Index completed, but exception errors in exception.log:
main.CRITICAL: RuntimeException: Search client is not set. in /var/www/html/vendor/magento/module-elasticsearch/SearchAdapter/ConnectionManager.php:90

`Exception: Warning: Undefined array key "elasticsuite" in /var/www/html/vendor/magento/module-elasticsearch/Elasticsearch5/Model/Client/ClientFactoryProxy.php on line 44 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:`

```
...
#0 /var/www/html/vendor/magento/module-elasticsearch/SearchAdapter/ConnectionManager.php(71): Magento\Elasticsearch\SearchAdapter\ConnectionManager->connect(Array)
#1 /var/www/html/vendor/magento/module-elasticsearch/Model/Adapter/Index/IndexNameResolver.php(67): Magento\Elasticsearch\SearchAdapter\ConnectionManager->getConnection(Array)
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Elasticsearch\Model\Adapter\Index\IndexNameResolver->__construct(Object(Magento\Elasticsearch\SearchAdapter\ConnectionManager), Object(Magento\Elasticsearch\Model\Config), Object(Magento\Framework\Logger\LoggerProxy), Array)
#3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Elastic...', Array)
#4 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Elastic...')
#5 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Elastic...')
#6 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Elastic...', NULL, 'indexNameResolv...', 'Magento\\Elastic...')
#7 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Elastic...', Array, Array)
#8 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Elastic...', Array, Array)
#9 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Elastic...', Array, Array)
#10 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Elastic...')
#11 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Elastic...')
#12 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Elastic...', NULL, 'adapter', 'Aligent\\AsyncEv...')
#13 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Aligent\\AsyncEv...', Array, Array)
#14 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Aligent\\AsyncEv...', Array, Array)
#15 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Aligent\\AsyncEv...', Array, Array)
#16 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Aligent\\AsyncEv...', Array)
#17 /var/www/html/vendor/magento/framework/Indexer/StructureFactory.php(33): Magento\Framework\ObjectManager\ObjectManager->create('\\Aligent\\AsyncE...', Array)
#18 /var/www/html/vendor/magento/module-indexer/Model/Indexer.php(414): Magento\Framework\Indexer\StructureFactory->create('\\Aligent\\AsyncE...')
#19 /var/www/html/vendor/magento/module-indexer/Model/Indexer.php(398): Magento\Indexer\Model\Indexer->getStructureInstance()
#20 /var/www/html/vendor/magento/module-indexer/Model/Indexer.php(443): Magento\Indexer\Model\Indexer->getActionInstance()
#21 /var/www/html/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(268): Magento\Indexer\Model\Indexer->reindexAll()
#22 /var/www/html/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(110): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#23 /var/www/html/vendor/symfony/console/Command/Command.php(298): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->___callParent('run', Array)
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/generated/code/Magento/Indexer/Console/Command/IndexerReindexCommand/Interceptor.php(86): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->___callPlugins('run', Array, Array)
#28 /var/www/html/vendor/symfony/console/Application.php(1040): Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
```

Thanks in advance.

**Comment by gowrizrh** [comment]
@joachimVT I'm not sure what the best way to approach this problem is as there's not a lot of tooling provided by Magento to abstract it for other search engines, however this is entirely because the search adapter trying to connect to ES during indexing.

Currently, it doesn't look like there is a way to support something other than ES.

Lazy loading the adapter via a proxy should skip the indexing from running (assuming you've set the indexing setting in admin to disable)

Could you try if fix in #61 solves the error and correctly skips the indexer from running given you've disabled it?

**Comment by joachimVT** [comment]
Hi @gowrizrh I can confirm this works, thanks for the quick update. Should we port this also to the mage os async events module ?

**Comment by gowrizrh** [comment]
Yes this will fix will be added as a new patch release.
